[2017-11-19 16:44:57,780: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-19 16:44:57,820: INFO/MainProcess] mingle: searching for neighbors
[2017-11-19 16:44:58,861: INFO/MainProcess] mingle: all alone
[2017-11-19 16:44:58,879: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-19 16:47:55,231: INFO/MainProcess] Received task: app.script_runner[fe0ab1b6-1577-4253-b7dc-36b964e0f560]  
[2017-11-19 16:50:40,521: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-19 16:50:40,547: INFO/MainProcess] mingle: searching for neighbors
[2017-11-19 16:50:41,588: INFO/MainProcess] mingle: all alone
[2017-11-19 16:50:41,615: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-19 16:54:53,043: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-19 16:54:53,057: INFO/MainProcess] mingle: searching for neighbors
[2017-11-19 16:54:54,082: INFO/MainProcess] mingle: all alone
[2017-11-19 16:54:54,100: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-19 16:55:39,813: INFO/MainProcess] Received task: app.script_runner[d1fb5b9d-ec24-49b6-896b-0d2774eb735d]  
[2017-11-19 16:59:37,665: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-19 16:59:37,690: INFO/MainProcess] mingle: searching for neighbors
[2017-11-19 16:59:38,727: INFO/MainProcess] mingle: all alone
[2017-11-19 16:59:38,743: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-19 17:00:36,755: INFO/MainProcess] Received task: app.script_runner[3bb076dd-cc74-43a6-94c5-ea42fe49cda2]  
[2017-11-19 17:02:09,372: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-19 17:02:09,387: INFO/MainProcess] mingle: searching for neighbors
[2017-11-19 17:02:10,408: INFO/MainProcess] mingle: all alone
[2017-11-19 17:02:10,424: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-19 17:02:42,477: INFO/MainProcess] Received task: app.script_runner[14a17033-2711-4c00-b982-06a02bedd87d]  
[2017-11-19 17:07:01,038: INFO/MainProcess] Received task: app.script_runner[443b5a9d-024f-4b9b-8ed5-90431d189605]  
[2017-11-19 17:10:28,040: INFO/MainProcess] Received task: app.script_runner[fd41ec4c-f8a6-4761-b32c-74edbd133633]  
[2017-11-19 17:12:01,767: INFO/MainProcess] Received task: app.script_runner[6452823a-c95c-4cd1-b43c-75c884979e19]  
[2017-11-19 17:21:03,668: INFO/MainProcess] Received task: app.script_runner[3cb087eb-3e84-4e4c-b928-7172b30e42bc]  
[2017-11-19 17:24:20,226: INFO/MainProcess] Received task: app.script_runner[ebe1a94f-c371-4789-b77f-c65d14168189]  
[2017-11-19 18:27:45,190: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-19 18:27:45,217: INFO/MainProcess] mingle: searching for neighbors
[2017-11-19 18:27:46,255: INFO/MainProcess] mingle: all alone
[2017-11-19 18:27:46,277: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-19 18:28:30,679: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-19 18:28:30,707: INFO/MainProcess] mingle: searching for neighbors
[2017-11-19 18:28:31,761: INFO/MainProcess] mingle: all alone
[2017-11-19 18:28:31,780: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-19 18:29:28,701: INFO/MainProcess] Received task: app.script_runner[c002a1c2-82f2-428d-b590-900eef877ad0]  
[2017-11-19 18:41:10,113: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-19 18:41:10,127: INFO/MainProcess] mingle: searching for neighbors
[2017-11-19 18:41:11,152: INFO/MainProcess] mingle: all alone
[2017-11-19 18:41:11,174: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-19 18:42:59,401: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-19 18:42:59,415: INFO/MainProcess] mingle: searching for neighbors
[2017-11-19 18:43:00,436: INFO/MainProcess] mingle: all alone
[2017-11-19 18:43:00,465: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-19 18:43:48,962: INFO/MainProcess] Received task: app.script_runner[77cbd84a-4be6-4f8d-861d-a73c5a93d1b9]  
[2017-11-19 18:59:31,590: INFO/MainProcess] Received task: app.script_runner[5c1384b8-d66c-469e-af0e-f7c21b1f7268]  
[2017-11-19 20:43:44,290: INFO/MainProcess] Received task: app.script_runner[b2eefa7c-7366-40c3-8e10-a91c19eb9264]  
[2017-11-20 07:53:24,352: INFO/MainProcess] Received task: app.script_runner[8d4ac698-7be8-4e89-a908-f7905caf3d22]  
[2017-11-20 08:00:59,502: INFO/MainProcess] Received task: app.script_runner[d809a887-5cdf-4f9a-822c-ee2f3b3d4cd5]  
[2017-11-20 13:33:14,524: INFO/MainProcess] Received task: app.script_runner[60eeb05b-6272-4bea-9348-145d8d6774ca]  
[2017-11-20 18:55:01,901: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-20 18:55:01,922: INFO/MainProcess] mingle: searching for neighbors
[2017-11-20 18:55:02,949: INFO/MainProcess] mingle: all alone
[2017-11-20 18:55:02,969: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-20 18:56:37,195: INFO/MainProcess] Received task: app.script_runner[94e5b935-6618-434d-9dd6-2ae731e5d06c]  
[2017-11-20 18:57:31,346: INFO/MainProcess] Received task: app.script_runner[595e7736-03da-4bba-9fdc-420910efa3f0]  
[2017-11-20 20:41:45,963: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-20 20:41:45,979: INFO/MainProcess] mingle: searching for neighbors
[2017-11-20 20:41:47,005: INFO/MainProcess] mingle: all alone
[2017-11-20 20:41:47,023: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-20 20:43:52,260: INFO/MainProcess] Received task: app.script_runner[f04365f2-2ac4-4dba-8737-c64c61387c19]  
[2017-11-21 07:55:51,590: INFO/MainProcess] Received task: app.script_runner[f8bec2af-22d9-46a0-beb3-e8df6f940af5]  
[2017-11-21 09:10:17,667: INFO/MainProcess] Received task: app.script_runner[2a36dba5-a8db-48e0-8dc0-3e3ec727a22b]  
[2017-11-21 09:45:21,398: INFO/MainProcess] Received task: app.script_runner[03d2d9c5-eeb1-4c56-b176-279c2ab05638]  
[2017-11-21 11:44:52,070: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-21 11:44:52,083: INFO/MainProcess] mingle: searching for neighbors
[2017-11-21 11:44:53,106: INFO/MainProcess] mingle: all alone
[2017-11-21 11:44:53,131: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-21 12:07:05,895: INFO/MainProcess] Received task: app.script_runner[0a74efe7-120f-4ae5-ade5-bc837666bd8f]  
[2017-11-21 12:08:23,812: INFO/MainProcess] Received task: app.script_runner[97e1dc6f-dcff-410d-b7e2-c9d5c8b5c317]  
[2017-11-21 12:09:41,041: INFO/MainProcess] Received task: app.script_runner[6498574f-5d37-434c-ac05-2ca74c6b7094]  
[2017-11-21 12:12:02,794: INFO/MainProcess] Received task: app.script_runner[6b572acb-d807-4bd5-94d3-3eff08646ed9]  
[2017-11-21 12:13:22,372: INFO/MainProcess] Received task: app.script_runner[2bf57ee4-479b-4a6e-9ebf-d499a3bb510c]  
[2017-11-21 12:15:34,254: INFO/MainProcess] Received task: app.script_runner[2f6c2a4f-548e-45cb-9ced-94967dd4bc1e]  
[2017-11-21 17:47:19,965: INFO/MainProcess] Received task: app.script_runner[f91faa3c-87ab-456f-a8be-d5eea9010539]  
[2017-11-21 17:54:41,321: INFO/MainProcess] Received task: app.script_runner[205405c6-1362-4ec6-ab42-41c06d0499f2]  
[2017-11-22 07:42:12,600: INFO/MainProcess] Received task: app.script_runner[40e39926-9ff3-47c0-a5cd-4a1b4f07ac41]  
[2017-11-22 08:50:06,514: INFO/MainProcess] Received task: app.script_runner[959b6054-1c9f-4866-8e88-2db86a1612f2]  
[2017-11-22 08:53:38,296: INFO/MainProcess] Received task: app.script_runner[5be27f6a-69a2-4430-81a4-a50717fa1559]  
[2017-11-22 09:11:29,914: INFO/MainProcess] Received task: app.script_runner[bbd12841-9262-4e6b-8328-03545fdfdd05]  
[2017-11-22 09:52:34,886: INFO/MainProcess] Received task: app.script_runner[91ea51d4-3811-44ef-b981-72758f451f2d]  
[2017-11-27 19:19:51,280: INFO/MainProcess] Received task: app.script_runner[35d39512-6045-4081-9426-2d8249cf1079]  
[2017-11-27 19:45:45,643: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-11-27 19:45:45,655: INFO/MainProcess] mingle: searching for neighbors
[2017-11-27 19:45:46,678: INFO/MainProcess] mingle: all alone
[2017-11-27 19:45:46,702: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-11-27 19:47:19,253: INFO/MainProcess] Received task: app.script_runner[33949124-4c24-4c71-8fc7-4ec8aa82a3f7]  
[2017-11-27 20:10:47,452: INFO/MainProcess] Received task: app.script_runner[ef37c582-a4fb-474a-9305-b18b1ab53584]  
[2017-11-27 21:10:20,241: INFO/MainProcess] Received task: app.script_runner[75ee5731-0c04-4b3b-b64c-16bf93dd3019]  
[2017-11-27 22:10:30,679: INFO/MainProcess] Received task: app.script_runner[c1f76df6-a9ca-4fde-a93f-7cb9fbf47ceb]  
[2017-11-28 10:19:33,173: INFO/MainProcess] Received task: app.script_runner[9bcfb461-3c61-45c8-85fc-54ab8fb63ab7]  
[2017-11-28 12:41:45,157: INFO/MainProcess] Received task: app.script_runner[24b49dbd-2da8-4b93-83d0-6fccb356e758]  
[2017-11-28 12:51:00,618: INFO/MainProcess] Received task: app.script_runner[078e5535-f080-4bae-ac4f-f00726909bbd]  
[2017-11-28 14:07:44,493: INFO/MainProcess] Received task: app.script_runner[404603a0-c5e6-4415-8c8e-e29c6e4b38aa]  
[2017-11-28 19:34:00,203: INFO/MainProcess] Received task: app.script_runner[985b7f41-674b-4b96-8c9d-7cd328ad9718]  
[2017-11-29 13:21:58,894: INFO/MainProcess] Received task: app.script_runner[70240825-f25f-4bac-9771-177084197b6a]  
[2017-11-29 13:23:31,643: INFO/MainProcess] Received task: app.script_runner[84fc2bfd-cbf8-428d-ab24-3853446d1fc2]  
[2017-11-29 14:22:41,539: INFO/MainProcess] Received task: app.script_runner[2da2bc55-1358-4f9b-9fb3-665e16960716]  
[2017-12-03 11:43:06,088: INFO/MainProcess] Received task: app.script_runner[9474c62d-1df1-4abe-837a-a4308f338074]  
[2017-12-03 11:44:43,006: INFO/MainProcess] Received task: app.script_runner[e775f337-a756-4e67-b236-23ed67a23e4c]  
[2017-12-03 13:35:28,167: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-12-03 13:35:28,179: INFO/MainProcess] mingle: searching for neighbors
[2017-12-03 13:35:29,202: INFO/MainProcess] mingle: all alone
[2017-12-03 13:35:29,240: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2017-12-03 16:33:10,058: INFO/MainProcess] Received task: app.script_runner[6ff6c2be-7c55-43fa-b9d4-d85065ae7855]  
[2017-12-03 17:13:30,586: INFO/MainProcess] Received task: app.script_runner[8913f30e-aeb3-4cd5-ba67-e0ceda07482c]  
[2017-12-03 17:52:33,441: INFO/MainProcess] Received task: app.script_runner[a3a6eb5c-f09b-4c8c-8cdc-aeb0c7358e63]  
[2017-12-03 19:52:23,855: INFO/MainProcess] Received task: app.script_runner[8826b22d-eb7f-491b-b3d5-05f2742edb9a]  
[2017-12-03 22:33:15,830: INFO/MainProcess] Received task: app.script_runner[794b92d8-8bfd-43f1-9478-b39529f56fcd]  
[2017-12-08 10:50:41,385: INFO/MainProcess] Received task: app.script_runner[f4397460-e6aa-4914-a95b-07e3bbe0c0c0]  
[2018-01-05 14:03:45,029: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2018-01-05 14:03:45,045: INFO/MainProcess] mingle: searching for neighbors
[2018-01-05 14:03:46,072: INFO/MainProcess] mingle: all alone
[2018-01-05 14:03:46,092: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2018-01-06 17:27:40,663: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

[2018-01-06 17:27:42,672: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds...

[2018-01-06 17:27:46,688: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds...

[2018-01-06 17:27:52,707: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds...

[2018-01-06 17:28:00,727: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds...

[2018-01-06 17:28:10,745: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds...

[2018-01-06 17:28:22,769: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds...

[2018-01-06 17:28:36,797: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds...

[2018-01-06 17:28:52,833: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds...

[2018-01-06 17:29:10,863: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 20.00 seconds...

[2018-01-06 17:29:30,897: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds...

[2018-01-06 17:29:52,931: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 24.00 seconds...

[2018-01-06 17:30:16,974: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 26.00 seconds...

[2018-01-06 17:30:43,017: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 28.00 seconds...

[2018-01-06 17:31:11,058: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 30.00 seconds...

[2018-01-06 17:31:41,102: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:32:13,148: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:32:45,191: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:33:17,239: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:33:49,288: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:34:21,333: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:34:53,381: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:35:25,430: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:35:57,477: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:36:29,519: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:37:01,565: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:37:33,607: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:38:05,654: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:38:37,703: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:39:09,746: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:39:41,795: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:40:13,844: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:40:45,890: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:41:17,938: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:41:49,979: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:42:22,027: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:42:54,076: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:43:26,122: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:43:58,170: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:44:30,216: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:45:02,272: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:45:34,320: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:46:06,363: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:46:38,420: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:47:10,465: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:47:42,513: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:48:14,562: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:48:46,612: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:49:18,657: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:49:50,704: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:50:22,754: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:50:54,798: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:51:26,847: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:51:58,892: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:52:30,944: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:53:02,999: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:53:35,049: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:54:07,098: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:54:39,148: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:55:11,198: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:55:43,243: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:56:15,291: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:56:47,348: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:57:19,394: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:57:51,442: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:58:23,486: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:58:55,527: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:59:27,575: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 17:59:59,623: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:00:31,674: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:01:03,721: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:01:35,769: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:02:07,815: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:02:39,860: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:03:11,903: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:03:43,945: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:04:15,990: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:04:48,034: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:05:20,081: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:05:52,121: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:06:24,165: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:06:56,210: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:07:28,259: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:08:00,304: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:08:32,352: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:09:04,395: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:09:36,442: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:10:08,487: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:10:40,535: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:11:12,584: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:11:44,629: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:12:16,672: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:12:48,716: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:13:20,765: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:13:52,813: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:14:24,860: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:14:56,912: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:15:28,958: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:16:01,000: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:16:33,042: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-06 18:17:05,090: CRITICAL/MainProcess] Unrecoverable error: OperationalError('[Errno 111] Connection refused',)
Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/connection.py", line 414, in _reraise_as_library_errors
    yield
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/connection.py", line 405, in ensure_connection
    callback)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/utils/functional.py", line 333, in retry_over_time
    return fun(*args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/connection.py", line 261, in connect
    return self.connection
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/amqp/connection.py", line 282, in connect
    self.transport.connect()
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/amqp/transport.py", line 109, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/amqp/transport.py", line 150, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/worker/consumer/connection.py", line 21, in start
    c.connection = c.connect()
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 407, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 414, in connection_for_read
    self.app.connection_for_read(heartbeat=heartbeat))
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 438, in ensure_connected
    callback=maybe_shutdown,
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/connection.py", line 405, in ensure_connection
    callback)
  File "/auto/pysw/cel63/python/3.4.1/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/connection.py", line 419, in _reraise_as_library_errors
    sys.exc_info()[2])
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/vine/five.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/connection.py", line 414, in _reraise_as_library_errors
    yield
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/connection.py", line 405, in ensure_connection
    callback)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/utils/functional.py", line 333, in retry_over_time
    return fun(*args, **kwargs)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/connection.py", line 261, in connect
    return self.connection
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/amqp/connection.py", line 282, in connect
    self.transport.connect()
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/amqp/transport.py", line 109, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/amqp/transport.py", line 150, in _connect
    self.sock.connect(sa)
kombu.exceptions.OperationalError: [Errno 111] Connection refused
[2018-01-09 10:13:40,431: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

[2018-01-09 10:13:42,440: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds...

[2018-01-09 10:13:46,456: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds...

[2018-01-09 10:13:52,473: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds...

[2018-01-09 10:14:00,491: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds...

[2018-01-09 10:14:10,509: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds...

[2018-01-09 10:14:22,531: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds...

[2018-01-09 10:14:36,557: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds...

[2018-01-09 10:14:52,586: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds...

[2018-01-09 10:15:10,616: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 20.00 seconds...

[2018-01-09 10:15:30,648: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds...

[2018-01-09 10:15:52,682: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 24.00 seconds...

[2018-01-09 10:16:16,717: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 26.00 seconds...

[2018-01-09 10:16:42,757: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 28.00 seconds...

[2018-01-09 10:17:10,797: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 30.00 seconds...

[2018-01-09 10:17:40,846: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:18:12,895: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:18:44,938: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:19:16,978: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:19:49,025: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:20:21,070: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:20:53,117: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:21:25,160: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:21:57,209: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:22:29,252: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:23:01,300: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:23:33,349: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:24:05,393: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:24:37,442: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:25:09,486: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:25:41,534: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:26:13,581: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:26:45,627: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:27:17,675: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:27:49,724: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:28:21,769: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:28:53,816: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:29:25,858: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:29:57,898: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:30:29,943: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:31:01,989: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:31:34,037: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:32:06,081: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:32:38,131: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:33:10,180: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:33:42,225: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:34:14,272: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:34:46,316: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:35:18,363: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:35:50,411: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:36:22,462: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:36:54,512: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:37:26,563: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:37:58,623: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:38:30,673: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:39:02,719: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:39:34,770: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:40:06,817: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:40:38,870: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:41:10,915: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:41:42,966: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:42:15,010: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:42:47,056: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:43:19,117: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:43:51,169: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:44:23,220: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:44:55,270: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:45:27,322: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:45:59,372: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:46:31,422: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:47:03,472: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:47:35,517: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:48:07,571: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:48:39,634: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:49:11,676: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:49:43,719: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:50:15,771: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:50:47,815: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:51:19,866: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:51:51,917: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:52:23,966: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:52:56,012: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:53:28,061: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:54:00,120: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:54:32,171: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:55:04,219: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:55:36,274: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:56:08,323: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:56:40,371: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:57:12,422: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:57:44,467: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:58:16,520: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds...

[2018-01-09 10:58:48,591: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2018-01-09 10:58:48,955: INFO/MainProcess] mingle: searching for neighbors
[2018-01-09 10:58:49,980: INFO/MainProcess] mingle: all alone
[2018-01-09 10:58:50,111: INFO/MainProcess] worker@mastarke-lnx-v4.cisco.com ready.
[2018-01-09 12:09:34,514: INFO/MainProcess] Received task: app.script_runner[9ebb7271-b8de-4161-9fed-d4ce0a74331e]  
[2018-01-09 12:14:19,234: INFO/MainProcess] Received task: app.script_runner[37cad20b-fd3a-4716-92e1-e25db72fc580]  
[2018-01-09 12:34:44,034: INFO/MainProcess] Received task: app.script_runner[4b539249-549b-4f85-b03a-53db16025253]  
[2018-01-09 14:50:16,011: INFO/MainProcess] Received task: app.script_runner[6c087d84-7c37-4f0c-a16a-80dfe2115549]  
[2018-01-09 14:57:14,390: INFO/MainProcess] Received task: app.script_runner[2684a562-6b5a-45c5-9d4b-c065d9a3d0f8]  
[2018-01-10 11:37:10,092: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2018-01-10 11:37:10,102: INFO/MainProcess] mingle: searching for neighbors
[2018-01-10 11:37:11,120: INFO/MainProcess] mingle: all alone
[2018-01-10 11:37:11,136: INFO/MainProcess] worker@mastarke-lnx-v4.cisco.com ready.
[2018-01-10 11:37:11,137: INFO/MainProcess] Received task: app.script_runner[737f99a9-1e79-4cf1-92ed-fdeab77a8db0]  
[2018-01-10 13:33:54,943: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2018-01-10 13:33:54,952: INFO/MainProcess] mingle: searching for neighbors
[2018-01-10 13:33:55,971: INFO/MainProcess] mingle: all alone
[2018-01-10 13:33:55,989: INFO/MainProcess] worker@mastarke-lnx-v4.cisco.com ready.
[2018-01-10 13:36:23,599: INFO/MainProcess] Received task: app.script_runner[f486ab79-17bc-4805-a1d6-65ccea76ae90]  
[2018-01-10 14:41:23,030: INFO/MainProcess] Received task: app.script_runner[45c1cf0b-34ca-46dd-8976-b314cbf7a37f]  
[2018-01-11 13:59:19,775: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2018-01-11 13:59:19,786: INFO/MainProcess] mingle: searching for neighbors
[2018-01-11 13:59:20,805: INFO/MainProcess] mingle: all alone
[2018-01-11 13:59:20,819: INFO/MainProcess] worker@mastarke-lnx-v4.cisco.com ready.
[2018-01-11 16:17:28,420: INFO/MainProcess] Received task: app.script_runner[b0fd4932-9df1-458c-9374-aee4f0c2c977]  
[2018-01-11 17:26:43,622: INFO/MainProcess] Received task: app.script_runner[5a3a7083-540d-4d08-815b-baa311ba3272]  
[2018-01-11 17:46:06,138: INFO/MainProcess] Received task: app.script_runner[311c8d6b-d6a5-45e2-8a07-33e571955488]  
[2018-01-12 10:08:53,871: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2018-01-12 10:08:53,886: INFO/MainProcess] mingle: searching for neighbors
[2018-01-12 10:08:54,909: INFO/MainProcess] mingle: all alone
[2018-01-12 10:08:54,926: WARNING/MainProcess] /ws/mastarke-sjc/pyats2/lib/python3.4/site-packages/kombu/pidbox.py:71: UserWarning: A node named worker@mastarke-lnx-v2 is already using this process mailbox!

Maybe you forgot to shutdown the other node or did not do so properly?
Or if you meant to start multiple nodes on the same host please make sure
you give each node a unique node name!

  warnings.warn(W_PIDBOX_IN_USE.format(node=self))
[2018-01-12 10:08:54,936: INFO/MainProcess] worker@mastarke-lnx-v2 ready.
[2018-01-12 10:10:38,602: INFO/MainProcess] Received task: app.script_runner[a7e8f93e-9821-42d8-8f3a-70fa31e31998]  
[2018-01-12 10:13:42,185: INFO/MainProcess] Received task: app.script_runner[f7635444-347b-4686-a463-a37f2c3c5f05]  
[2018-01-12 10:18:50,121: INFO/MainProcess] Received task: app.script_runner[23cf6e7d-f7fb-4f22-bd4b-0da58c4587b6]  
[2018-01-12 10:21:30,795: INFO/MainProcess] Received task: app.script_runner[d3ae3ac0-d41f-4abd-99ab-fc4518c0527a]  
[2018-01-12 10:29:55,095: INFO/MainProcess] Received task: app.script_runner[4f3c8c85-3f1f-4b13-ac93-83300205310d]  
[2018-01-12 10:32:35,554: INFO/MainProcess] Received task: app.script_runner[8b9cebad-fe5a-4f0d-88e2-df41f269ef79]  
[2018-01-13 08:48:01,186: INFO/MainProcess] Received task: app.script_runner[2bfa6c71-1901-43ff-8941-b271aae076c1]  
[2018-01-13 09:24:24,226: INFO/MainProcess] Received task: app.script_runner[62bd3ad0-3385-4887-b9ed-9a7e1dcfec53]  
[2018-01-22 17:13:33,272: INFO/MainProcess] Received task: app.script_runner[370492ee-090d-488e-bec8-5ad589620987]  
[2018-01-31 10:44:19,886: INFO/MainProcess] Received task: app.script_runner[56d56242-c072-4307-9140-d74414491361]  
[2018-02-01 14:27:47,379: INFO/MainProcess] Received task: app.script_runner[06a2b7cf-1ceb-4f12-90c8-b4351e7c6c83]  
[2018-02-07 12:54:43,107: INFO/MainProcess] Received task: app.script_runner[99f81333-a53f-4f96-9003-44ac431d90d7]  
[2018-02-07 13:55:58,151: INFO/MainProcess] Received task: app.script_runner[a89c15cb-e2f2-4830-9101-f9ef69e4a8da]  
[2018-02-07 13:59:45,396: INFO/MainProcess] Received task: app.script_runner[4ebad117-81cd-4bd2-912f-a500f49ecc46]  
[2018-02-07 14:11:32,764: INFO/MainProcess] Received task: app.script_runner[121c70d9-a6bf-42f8-a290-69c2b1c385d8]  
[2018-02-12 01:26:02,169: INFO/MainProcess] Received task: app.script_runner[92bf2d6d-3b97-4705-a588-5cfed283008d]  
